apiVersion: v1
kind: Namespace
metadata:
  name: cilsy-prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cilsy-prod
  name: blog-prod
  labels:
    app: blog-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-prod
  template:
    metadata:
      labels:
        app: blog-prod
    spec:
      containers:
      - name: blog-prod
        image: hansenfernando/cilsyblog-prod
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  namespace: cilsy-prod      
  name: blog-svc-prod
spec:
  selector:
    app: blog-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: cilsy-prod
  name: blog-ingress-prod
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "blog-prod-cookie"
     nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/affinity-mode: persistent
     nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: cilsyblog.hansenfernando.xyz      
    http:
      paths:
        - backend:
             serviceName: blog-svc-prod
             servicePort: 80
